version: '3.9'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: library/postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parser_project

  redis:
    image: library/redis:alpine

  celery:
    restart: always
    build: ./backend
    command: celery -A config worker -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    restart: always
    build: ./backend
    command: celery -A config beat -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
      - celery

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: