# Generated by Django 4.1.4 on 2022-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=50, unique=True, verbose_name='Удаленный идентификатор')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Описание')),
                ('created', models.DateTimeField(verbose_name='Время добавления')),
                ('link', models.URLField(verbose_name='Ссылка на рекламу')),
                ('category', models.CharField(max_length=100, verbose_name='Категория рекламы')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Содержимое рекламы',
                'verbose_name_plural': 'Содержимое реклам',
            },
        ),
    ]
