# Generated by Django 4.1.4 on 2022-12-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
