# Generated by Django 4.1.4 on 2022-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Описание'),
        ),
    ]
